// Generated by CoffeeScript 1.3.3
(function() {
  var loggerManager;

  loggerManager = require('./logger_factory');

  exports.getLogger = loggerManager.getLogger;

  exports.initLogger = loggerManager.initLogger;

}).call(this);
