// Generated by CoffeeScript 1.3.3
(function() {
  var Logger, loggerMap;

  Logger = require('./logger').Logger;

  loggerMap = {};

  exports.getLogger = function(name) {
    return loggerMap[name];
  };

  exports.initLogger = function(confArray) {
    var logger, loggerConf, root, _i, _len, _ref;
    root = confArray.root;
    _ref = confArray.loggers;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      loggerConf = _ref[_i];
      logger = new Logger(root, loggerConf, confArray);
      loggerMap[loggerConf.name] = logger;
    }
  };

}).call(this);
