// Generated by CoffeeScript 1.3.3
(function() {
  var Layout;

  Layout = (function() {

    function Layout() {}

    Layout.prototype.format = function(level, msg) {};

    return Layout;

  })();

  exports.Layout = Layout;

}).call(this);
