// Generated by CoffeeScript 1.3.3
(function() {
  var Layout, SimpleLayout,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Layout = require('./layout').Layout;

  SimpleLayout = (function(_super) {

    __extends(SimpleLayout, _super);

    function SimpleLayout() {
      return SimpleLayout.__super__.constructor.apply(this, arguments);
    }

    SimpleLayout.prototype.format = function(level, msg) {
      return "[" + level.toUpperCase() + "]" + ("" + msg);
    };

    return SimpleLayout;

  })(Layout);

  exports.SimpleLayout = SimpleLayout;

}).call(this);
