// Generated by CoffeeScript 1.3.3
(function() {
  var LayoutAttachable, SimpleLayout;

  SimpleLayout = require('../layout/simple_layout').SimpleLayout;

  LayoutAttachable = {
    setLayout: function(layout) {
      if ("SimpleLayout" === layout) {
        this.layout = new SimpleLayout;
      }
    },
    format: function(level, msg) {
      if (this.layout) {
        msg = this.layout.format(level, msg);
      }
      return msg;
    }
  };

  exports.LayoutAttachable = LayoutAttachable;

}).call(this);
