// Generated by CoffeeScript 1.3.3
(function() {
  var conf, log, logger;

  conf = {
    "root": "",
    "appenders": {
      "sentryAppender": {
        "disable": false,
        "type": "SentryAppender",
        "properties": {
          "dsn": "" + dsn
        }
      },
      "consoleAppender": {
        "type": "ConsoleAppender",
        "properties": {
          "layout": "SimpleLayout"
        }
      }
    },
    "loggers": [
      {
        "name": "example",
        "level": "all",
        "appenderRefs": ["sentryAppender", "consoleAppender"]
      }
    ]
  };

  log = require('../index.js');

  log.initLogger(conf);

  logger = log.getLogger("example");

  logger.error("error field1 field2 ...\n");

}).call(this);
