// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractAppender, LayoutAttachable, LevelAble, Module,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LayoutAttachable = require('../core/layout_attachable').LayoutAttachable;

  LevelAble = require('../core/level').LevelAble;

  Module = require('../core/module').Module;

  AbstractAppender = (function(_super) {

    __extends(AbstractAppender, _super);

    function AbstractAppender() {
      return AbstractAppender.__super__.constructor.apply(this, arguments);
    }

    AbstractAppender.include(LayoutAttachable);

    AbstractAppender.include(LevelAble);

    AbstractAppender.prototype.append = function(loggerName, level, msg) {
      throw new Error("append in null");
    };

    return AbstractAppender;

  })(Module);

  exports.AbstractAppender = AbstractAppender;

}).call(this);
