// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractAppender, ConsoleAppender, LevelUtil, util,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractAppender = require('./abstract_appender').AbstractAppender;

  LevelUtil = require('../core/level').LevelUtil;

  util = require('util');

  ConsoleAppender = (function(_super) {

    __extends(ConsoleAppender, _super);

    function ConsoleAppender(params) {
      return;
    }

    ConsoleAppender.prototype.append = function(loggerName, level, msg) {
      if (util.isArray(msg)) {
        msg = msg.join(',') + '\n';
      } else {
        msg += '\n';
      }
      msg = this.format(level, msg);
      if (LevelUtil.isError(level)) {
        process.stderr.write(msg);
      } else {
        process.stdout.write(msg);
      }
    };

    return ConsoleAppender;

  })(AbstractAppender);

  exports.ConsoleAppender = ConsoleAppender;

}).call(this);
